name = "your-awesome-website"
type = "webpack"
account_id = "your-account-id"
route = ""
zone_id = ""
compatibility_date = "2023-05-18"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"